# Generated by Django 4.2.13 on 2024-07-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vista_previa', '0007_moneda_alter_fondo_cotizado_originalmente'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='calificadora_de_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fondo',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vista_previa.calificacion'),
        ),
        migrations.AlterField(
            model_name='fondo',
            name='calificadora_de_riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vista_previa.calificadora_de_riesgo'),
        ),
    ]
