# Generated by Django 4.2.13 on 2024-07-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vista_previa', '0008_calificacion_calificadora_de_riesgo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pais_sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fondo',
            name='pais_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vista_previa.pais_sede'),
        ),
    ]
