# Generated by Django 4.2.13 on 2024-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_previa', '0011_benchmark_cuota_duration_plazo_liquidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='fecha_de_calificacion',
            field=models.DateField(verbose_name='Fecha de Calificacion'),
        ),
        migrations.AlterField(
            model_name='fondo',
            name='fecha_inicio_del_fondo',
            field=models.DateField(verbose_name='Fecha de inicio del Fondo'),
        ),
    ]
