# Generated by Django 4.2.13 on 2024-07-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vista_previa", "0012_alter_fondo_fecha_de_calificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fondo",
            name="bolsa",
            field=models.CharField(
                choices=[
                    ("NA", "ArgNA"),
                    ("NA2", "ArgNA2"),
                    ("B", "BYMA"),
                    ("RM", "Rofex-Matba"),
                    ("MV", "MAV"),
                ],
                default="ArgNA",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="fondo",
            name="estado",
            field=models.CharField(
                choices=[("A", "Activo"), ("B", "Cancelado")],
                default="Activo",
                max_length=200,
            ),
        ),
    ]
