# Generated by Django 4.2.13 on 2024-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_previa', '0013_alter_fondo_bolsa_alter_fondo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', max_length=200),
        ),
    ]
