# Generated by Django 4.2.13 on 2024-07-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='calificadora_de_riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='horizonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pais_sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='plazo_liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sociedad_depositaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sociedad_gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clase', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_economatica', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_de_calificacion', models.DateField(verbose_name='Fecha de Calificacion')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', max_length=200)),
                ('bolsa', models.CharField(choices=[('NA', 'ArgNA'), ('NA2', 'ArgNA2'), ('B', 'BYMA'), ('RM', 'Rofex-Matba'), ('MV', 'MAV')], default='ArgNA', max_length=200)),
                ('codigo_cafci', models.CharField(max_length=200)),
                ('comision_de_ingreso', models.CharField(max_length=200)),
                ('honorarios_de_administración', models.CharField(max_length=200)),
                ('otros', models.CharField(max_length=200)),
                ('comision_de_egreso', models.CharField(max_length=200)),
                ('comision_de_transferencia', models.CharField(max_length=200)),
                ('gastos_ordinarios_de_gestión', models.CharField(max_length=200)),
                ('cobra_comision_por_perfomance', models.CharField(max_length=200)),
                ('inversion_minima', models.CharField(max_length=200)),
                ('fecha_inicio_del_fondo', models.DateField(verbose_name='Fecha de inicio del Fondo')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.benchmark')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.calificacion')),
                ('calificadora_de_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.calificadora_de_riesgo')),
                ('cotizado_originalmente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.moneda')),
                ('cuota_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.cuota')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.duration')),
                ('horizonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.horizonte')),
                ('pais_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.pais_sede')),
                ('plazo_de_liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.plazo_liquidacion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.region')),
                ('sociedad_depositária', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.sociedad_depositaria')),
                ('sociedad_gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.sociedad_gerente')),
                ('tipo_de_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.tipo_de_activo')),
                ('tipo_de_inversión', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_generales.tipo_de_inversion')),
            ],
        ),
    ]
