# Generated by Django 4.2.13 on 2024-07-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(choices=[('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Uruguay', 'Uruguay'), ('Chile', 'Chile'), ('Bolivia', 'Bolivia'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Otro', 'Otro')], default='Argentina', max_length=200)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Ciudad Autónoma de Buenos Aires', 'Ciudad Autónoma de Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán'), ('Otro', 'Otro')], default='Buenos Aires', max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=200)),
                ('domicilio', models.CharField(blank=True, max_length=200)),
                ('codigo_postal', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
