# Generated by Django 4.2.13 on 2024-07-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vista_previa', '0014_alter_fondo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha')),
                ('cuota', models.CharField(max_length=200, null=True)),
                ('patrimonio', models.CharField(max_length=200, null=True)),
                ('market_share', models.CharField(max_length=200, null=True)),
                ('cantidad_de_cuotas', models.CharField(max_length=200, null=True)),
                ('fondo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vista_previa.fondo')),
            ],
            options={
                'db_table': 'cotizacion_vcp',
            },
        ),
    ]
