# Generated by Django 4.2.13 on 2024-07-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField(verbose_name='Fecha')),
                ('cuota', models.CharField(max_length=200, null=True)),
                ('patrimonio', models.CharField(max_length=200, null=True)),
                ('market_share', models.CharField(max_length=200, null=True)),
                ('cantidad_de_cuotas', models.CharField(max_length=200, null=True)),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=200)),
                ('fondo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_generales.fondo')),
            ],
            options={
                'db_table': 'vcp',
            },
        ),
    ]
